# Generated by Django 2.0.3 on 2018-04-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20180402_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatereports',
            name='batch',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=30),
            preserve_default=False,
        ),
    ]
