# Generated by Django 2.0.3 on 2018-04-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_generatereports_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatereports',
            name='batch',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=30),
        ),
    ]
