# Generated by Django 2.0.3 on 2018-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180426_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatereports',
            name='batch',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening'), ('', 'All')], default='', max_length=30),
        ),
    ]
