# Generated by Django 2.0.3 on 2018-03-15 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180315_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 15, 2, 34, 20, 515975, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='registration_upto',
            field=models.DateField(default=datetime.datetime(2018, 3, 15, 2, 34, 35, 164494, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
