# Generated by Django 2.0.3 on 2018-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180316_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.IntegerField(unique=True),
        ),
    ]
