# Generated by Django 2.0.3 on 2018-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180316_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
