# Generated by Django 2.0.3 on 2018-03-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180316_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.FileField(default='default.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
