# Generated by Django 2.0.3 on 2018-03-16 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='admitted_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 3, 16, 15, 11, 7, 553526, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
