# Generated by Django 2.0.3 on 2018-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20180316_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.FileField(blank=True, upload_to='photos/'),
        ),
    ]
