# Generated by Django 2.0.3 on 2018-04-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='notification',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
