# Generated by Django 2.0.3 on 2018-04-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20180402_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='notification',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
