# Generated by Django 2.0.3 on 2018-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20180402_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fee_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=30),
        ),
    ]
