# Generated by Django 2.0.3 on 2018-04-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20180404_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='medical_history',
            field=models.CharField(blank=True, default='None', max_length=300),
        ),
    ]
