# Generated by Django 2.0.3 on 2018-04-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20180427_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(default='dd/mm/yyyy'),
        ),
    ]
