# Generated by Django 2.0.3 on 2018-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20180427_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='batch',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=30),
        ),
    ]
