# Generated by Django 2.0.3 on 2018-05-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20180509_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default='dd/mm/yyyy'),
        ),
    ]
